/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package scc210game;

import scc210game.render.EngineSetup;

public class App {
    public static void main(String[] args) {
        System.out.println("Hello world");
        EngineSetup.runForever();
    }
}
